services:
  app:
    container_name: java-pdf-work
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /app
    environment:
      PDF_OUT_DIR: /app/output
      PDF_MERGE_INPUT_DIR: /app/input/merge
      PDF_SPLIT_INPUT_DIR: /app/input/split
    volumes:
      - ./src:/app/src
      - ${PDF_OUT_DIR}:/app/output
      - ${PDF_MERGE_INPUT_DIR}:/app/input/merge
      - ${PDF_SPLIT_INPUT_DIR}:/app/input/split
    tty: true
    stdin_open: true
